apiVersion: v1
kind: Service
metadata:
  name: generatemanifestfiles
  namespace: default
  labels:
    app.kubernetes.io/name: generatemanifestfiles
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: generatemanifestfiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80